name: dart_code
description: A package for creating valid and formatted code, e.g. when writing code builders.
version: 0.2.2
repository: https://github.com/domain-centric/dart_code

topics:
  - code-generation
  - source-code
  - dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_style: ^3.0.1

dev_dependencies:
  test: ^1.21.5
  lints: ^5.1.1
  shouldly: ^0.5.0+1
