name: dart_code
description: A new Flutter package project.
version: 0.0.1
author: Nils ten Hoeve
homepage: https://github.com/efficientyboosters/dart_code

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.0

flutter:


