name: dart_code
description: A package for creating valid and formatted code, e.g. when writing code builders.
version: 0.1.6
repository: https://github.com/domain-centric/dart_code

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_style: ^2.2.3

dev_dependencies:
  test: ^1.21.5
  lints: ^2.0.1

flutter: