name: dart_code
description: A package for creating valid and formatted code, e.g. when writing code builders.
version: 0.1.10
repository: https://github.com/domain-centric/dart_code

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  dart_style: ^2.2.3

dev_dependencies:
  test: ^1.21.5
  lints: ^2.0.1
  given_when_then_unit_test: ^0.0.4
  shouldly: ^0.5.0+1
