name: dart_code
description: A package for creating valid and formatted code, e.g. when writing code builders.
version: 0.0.6
repository: https://github.com/efficientyboosters/dart_code
homepage: https://github.com/efficientyboosters/dart_code

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_style: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.0

flutter:


