name: dart_code
description: A package for creating valid and formatted code, e.g. when writing code builders.
version: 0.1.2
repository: https://github.com/domain-centric/dart_code

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_style: ^2.0.1

dev_dependencies:
  test: 1.17.3

flutter: